addSbtPlugin("org.scoverage"  % "sbt-scoverage"   % "1.9.3")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"  % "1.5.10")
addSbtPlugin("ch.epfl.scala"  % "sbt-bloop"       % "1.5.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"        % "2.2.24")
addSbtPlugin("com.eed3si9n"   % "sbt-unidoc"      % "0.4.3")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"    % "0.9.34")
addSbtPlugin("dev.zio"        % "zio-sbt-website" % "0.1.5+14-f39b7a47-SNAPSHOT")

resolvers += Resolver.sonatypeRepo("public")
