addSbtPlugin("org.scoverage" % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("com.geirsson"  % "sbt-ci-release" % "1.5.3")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop"      % "1.4.3")
addSbtPlugin("org.scalameta" % "sbt-mdoc"       % "2.2.7")
addSbtPlugin("com.github.sbt"  % "sbt-unidoc"     % "0.5.0")
