addSbtPlugin("org.scoverage" % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"   % "2.3.4")
addSbtPlugin("com.geirsson"  % "sbt-ci-release" % "1.5.2")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop"      % "1.4.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc"       % "2.2.0")
addSbtPlugin("com.eed3si9n"  % "sbt-unidoc"     % "0.4.3")
